import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import NextAuthSessionProvider from "@/providers/sessionProvider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <NextAuthSessionProvider>
            <html lang="pt-br">
            <body className={`${inter.className} flex flex-col justify-center items-center h-screen`}>{children}</body>
            </html>
        </NextAuthSessionProvider>
    );
}
